### ISSUE TITLE
Get Item image

### ISSUE THREAD

**Issue by DaleOC** [square/square-nodejs-sdk#101]
I am trying to get the Item image using "List Catalog" on client.catalogApi. Nothing is being returned. 
Is there another way to do this?

**Comment by zenmasterjobo** [comment]
hi @DaleOC 

Items returned in the the response that have images will have a field set in their `itemData` called imageIds https://developer.squareup.com/reference/square/objects/CatalogItem#definition__property-image_ids

Images are just objects in the catalog API, so you can then query the `RetrieveCatalogObject` api and supply the desired imageID to then get the src url for the image.

In the future we suggest that you post questions on our [Developer Forums](developer.squareup.com/forums) as the forums are monitored by Square employees and you will receive a response within 48 hours. 

Cheers!
