### ISSUE TITLE
Number is not an Integer

### ISSUE THREAD

**Issue by theahmadzai** [square/square-nodejs-sdk#103]
**Describe the bug**
Getting this error that 700 is not an integer

**Screenshots**
![image](https://user-images.githubusercontent.com/9446563/190195216-c3634ce3-e225-4ef2-82d4-9899ea7a8688.png)
![image](https://user-images.githubusercontent.com/9446563/190194271-bb8b9fbf-0193-4b75-a334-e76de46fe1b0.png)

**Square SDK version**
SDK Version:  21.1.0

**Additional context**
Using react native first it was throwing an error that bigint unknown because it's unsupported yet so I pulled down a polyfill library for bigint it worked fine other methods seem to be working fine but when I call create payment I get this error that you see in the screenshot that it expects an integer but the value I give is like hardcoded Number(700)

I explored the SDK and I found that bigint schema is being used which is imported from the @apimatic/schema package, unfortunately, could not see the implementation there the package seems to be moved or broken.

**Comment by zenmasterjobo** [comment]
hi @theahmadzai,

Are you still experiencing this issue?

In your screenshot it looks like `700` is wrapped in `"` making it a string, and in this case throwing the error. Can you share how you are making the request to create payment?

**Comment by theahmadzai** [comment]
I'm not using this library on the frontend (react-native) now
