### ISSUE TITLE
General question about usage in react-native

### ISSUE THREAD

**Issue by theahmadzai** [square/square-nodejs-sdk#104]
I'm planning to use this lib directly in react native without a server of course server for the OAuth and onboarding part but once have the token planning to use it directly from the client-side do you guys recommend this approach and what are the pros and cons of using like that keeping the caching and rate limiting from the square side in mind. 

Thanks

**Comment by zenmasterjobo** [comment]
hi @theahmadzai,

Can you share more about which APIs your app would be using? As for storing the User's access token on the device, we would recommend that your App use the [PKCE Oauth flow](https://developer.squareup.com/docs/oauth-api/overview#pkce-flow) which we recently released support for.

**Comment by theahmadzai** [comment]
Not using this lib on the frontend anymore
