### ISSUE TITLE
Ecom visibility and availability are missing from the SDK 

### ISSUE THREAD

**Issue by doron2402** [square/square-nodejs-sdk#113]
**Describe the bug**
When using the [List Catalog](https://developer.squareup.com/explorer/square/catalog-api/list-catalog) for fetching items the api doesn't return the EcomVisibility values (Determines item visibility in Ecom (Online Store) and Online Checkout.).

**Expected behavior**
It should return the same response as the API, seems like when parsing the response the API remove those fields.

**To Reproduce**
Steps to reproduce the bug:
1. Get a valid token
2. Make the call using the SDK vs curl

 
**Screenshots**
Curl:
<img width="342" alt="Screen Shot 2022-12-01 at 2 44 21 PM" src="https://user-images.githubusercontent.com/2269831/205068404-89cec8b2-749b-4813-b4bc-643554588bbd.png">

**Square SDK version**
```
"square": "^24.0.0"
```

**Comment by castrostevenfox** [comment]
same issues on 25.1.0

**Comment by castrostevenfox** [comment]
The API Explorer shows the ecom fields, but the actual response is missing them.
Only with the http endpoints we get those results.

**Comment by castrostevenfox** [comment]
Someone made PR 
https://github.com/square/square-nodejs-sdk/pull/112
Can it be approved ?

**Comment by zenmasterjobo** [comment]
hi @castrostevenfox  and @doron2402 

I have notified our SDK team and we are investigating a fix for this! Thanks for opening an issue and calling it out. Unfortunately our SDKs are generated, so the changes we need to implement are different from how they are presented in the PR.

Thanks for your patience, and I will check back here with updates when I have them!

Cheers

**Comment by doron2402** [comment]
Any update on that?

**Comment by zenmasterjobo** [comment]
These ecom fields were not intended to be released publicly, and will not be available on the API. Apologies for any confusion and inconvenience!
