### ISSUE TITLE
Redeem reward codes with Orders API

### ISSUE THREAD

**Issue by michaelcaterisano** [square/square-nodejs-sdk#14]
Is it possible to redeem a 6-digit reward code generated by Square Marketing through the API? It's possible to redeem these at a POS, but I've not found a way to validate and redeem reward codes through the API.

**Comment by StephenJosey** [comment]
No, there is not a way to do this through the API at this time. I will close this out as this is more a feature request for the API instead of the SDK unfortunately. I'll pass the feedback along to the appropriate teams.

**Comment by michaelcaterisano** [comment]
Thanks. Is there a better place to put requests like these?

**Comment by StephenJosey** [comment]
Definitely! Sorry I didn't mention in my previous comment. Feel free to post this in our public developer forums as a feature request: https://developer.squareup.com/forums/. Thanks, and my apologies 😄
