### ISSUE TITLE
CORS issues when sending requests from a front end app

### ISSUE THREAD

**Issue by mbates** [square/square-nodejs-sdk#19]
I am trying to use the catalog API with my angular app, but requests are failing with CORS Missing Allow Origin.

If I use curl to send GET requests to the sandbox API I get the expected result. But when I send the same request from angular (which includes the origin and referer headers) the response is a 403 with "CORS Missing Allow Origin"

This works
```
 curl "https://connect.squareupsandbox.com/v2/catalog/list" -H "User-Agent: Square-TypeScript-SDK/8.0.0" -H "Accept: application/json" -H "Accept-Language: en-US,en;q=0.5" --compressed -H "authorization: Bearer SANDBOX_ACCESS_TOKEN" -H "Square-Version: 2020-12-16" -H "Connection: keep-alive"
 ```

This fails (the command was created from firefox devtools > copy as curl)
```
curl "https://connect.squareupsandbox.com/v2/catalog/list" -H "User-Agent: Square-TypeScript-SDK/8.0.0" -H "Accept: application/json" -H "Accept-Language: en-US,en;q=0.5" --compressed -H "authorization: Bearer SANDBOX_ACCESS_TOKEN" -H "Square-Version: 2020-12-16" -H "Origin: http://dev.domain.com" -H "Connection: keep-alive" -H "Referer: http://dev.domain.com/product-list"
```

How can I use your APIs as a backend for a webapp?

**Comment by StephenJosey** [comment]
So it sounds like you're attempting to call the APIs from Angular (which is a frontend framework), which we do not currently allow and will block. If you call our APIs from the frontend, you would be exposing your secret access token to anyone who uses your app. You would need to use a backend language (PHP, Node.js, etc) to call our APIs from.
