### ISSUE TITLE
batchRetrieveOrders returned an error Error: The response did not match the response schema.

### ISSUE THREAD

**Issue by jjc235** [square/square-nodejs-sdk#23]
Running batchRetrieveOrders doesn't work approx 30% of the time.

The following output is given by the sdk.

Given value: {"location_id":"REDACTED","amount_money":{"amount":5,"currency":"USD"},"receivable_id":"REDACTED"}
Type: 'object'
Expected type: 'Lazy<Object<{locationId,description,amountMoney,receivableId}>>'
Path: orders › 37 › refunds › 0 › additional_recipients › 0

**Comment by StephenJosey** [comment]
Can you share a code snippet on how you're calling it? So far I'm unable to replicate this error. Can you also share an `order_id` so I can take a look at what exactly is being returned?

**Comment by jjc235** [comment]
Here's the response that includes the call since 8.0.  This has been
happening since 8.0 when I first reported it- it's still happening in 9.1.

{"error":{"request":{"method":"POST","url":"https://connect.squareup.com/v2/orders/batch-retrieve","headers":{"user-agent":"Square-TypeScript-SDK/8.0.0","content-type":"application/json","authorization":"Bearer
REDACTED","Square-Version":"2020-12-16","accept":"application/json"},"body":{"type":"text","content":"{\"location_id\":\"HPK6YH0WJWSZ5\",\"order_ids\":[\"d7iHF61AoqfgDNbgwNSLnnreV\",\"ZP7KJL0b4RSMqAzoy0Hetu7eV\",\"DM3yPdeKzEW9m2xav0dR4eweV\",\"zWf7zjTx3umPl1r1aL4juAiYFa4F\",\"FlL6H8RNv0i48OoOvA7dqVweV\",\"9DX78WLIxPlvWGKKHawpgQqC9e4F\",\"h7SDofeVd5YJ4YSb2tv7AL7sGa4F\",\"x79r9JvR8qzeoTtSU9Ayks5eV\",\"T2nTZc8mFJDAvLpxCNuyy0n7yb4F\",\"VNU8JyjnfitIOT8iKYB584Este4F\",\"BNeD6dIfL8Aqzk2CcwabwFoeV\",\"9VOotJ3JTcwEKl8wlhfXk4tmpZ4F\",\"n2DmXgqQBUldWNqW0KgEtMfeV\",\"JVVRRQHdJ9J49xNJwddO2WaOjb4F\",\"LQDAz1CQQR433kwD2CA8oOoeV\",\"vysQEWztSPuVkKqlg1Ddxbvvye4F\",\"53Rd89G3n8u9i8FOFtgAM1xeV\",\"ZrCuwngSs55z0deyCgiHhYIkfa4F\",\"dB9bR8Ey0vnhGRnmQb9MskueV\",\"jWZad31MetPQEGdNHRNEcksglb4F\",\"Deckh5KwW76d5fUM7HE9qb6eV\",\"FNYUf7jMazZcr5HAWwswc9R0ta4F\",\"tx9ZB8xK4RkszYAS3bhrZI9eV\",\"rehxfnng1ahLd3rLGZXn5v8tUd4F\",\"hTdf94kMo4jNR4jyUpzXegAfV\",\"dDdsjzYNeeu0WlPAPkiJgmdrdd4F\",\"fmiqbm5lHk5gQI7o4L5ZW4uW0Z4F\",\"TYRqJPS6GRgbUmxCxPKJfgseV\",\"pV7eQqrN8w6WJFDryqkrEZgOvf4F\",\"ljxP5cHf52DTvYel64hjvfjGvh4F\",\"dzJkg6QOGsrnkKOnKvzl3VCl7h4F\",\"f2NssKALBgetwsh2s8vJxomeV\",\"lLfIrIYRbbUr8K2yZjgrxKE6Me4F\",\"nY3fgP1IPWjioPSVOes3Gta4ph4F\"]}"}},"statusCode":200,"headers":{"date":"Tue,
05 Jan 2021 18:51:38
GMT","frame-options":"DENY","x-frame-options":"DENY","x-content-type-options":"nosniff","x-xss-protection":"1;
mode=block","content-type":"application/json;charset=utf-8","square-version":"2020-12-16","vary":"Accept-Encoding,
User-Agent","content-length":"76652","strict-transport-security":"max-age=631152000;
includeSubDomains; preload","connection":"close"},"body":"{\"orders\":
[{\"id\": \"d7iHF61AoqfgDNbgwNSLnnreV\",\"location_id\":
\"HPK6YH0WJWSZ5\",\"created_at\":
\"2020-12-17T22:28:30.000Z\",\"updated_at\":
\"2020-12-17T22:28:30.000Z\",\"state\":
\"COMPLETED\",\"total_tax_money\": {\"amount\": 0,\"currency\":
\"USD\"},\"total_discount_money\": {\"amount\": 0,\"currency\":
\"USD\"},\"total_tip_money\": {\"amount\": 0,\"currency\":
\"USD\"},\"total_money\": {\"amount\": 0,\"currency\":
\"USD\"},\"closed_at\":
\"2020-12-17T22:28:31.000Z\",\"total_service_charge_money\":
{\"amount\": 0,\"currency\": \"USD\"},\"returns\":
[{\"source_order_id\":
\"ZP7KJL0b4RSMqAzoy0Hetu7eV\",\"return_line_items\": [{\"uid\":
\"4EFB34EC-9764-4DE0-B4ED-83C767838286\",\"source_line_item_uid\":
\"B4709840-E34C-469D-9923-A41F4D8D0992\",\"name\": \"Classic
Black\",\"quantity\": \"1\",\"catalog_object_id\":
\"AQFIPTHRMS4PCUVMHIA5MC3G\",\"variation_name\": \"24
oz.\",\"item_type\": \"ITEM\",\"return_modifiers\": [{\"uid\":
\"DE90774A-3FA1-4ADD-AFC1-26BEF9CB8E02\",\"catalog_object_id\":
\"ELHEKJUZDB4ZBUFQF77W2B37\",\"name\": \"Cold\",\"base_price_money\":
{\"amount\": 0,\"currency\": \"USD\"},\"total_price_money\":
{\"amount\": 0,\"currency\": \"USD\"}},{\"uid\":
\"0AB8CB0F-C590-4B12-AD33-B0BD918E1B86\",\"catalog_object_id\":
\"IJ2EUD7ZUUYJDEADVITGPJGV\",\"name\": \"Boba\",\"base_price_money\":
{\"amount\": 50,\"currency\": \"USD\"},\"total_price_money\":
{\"amount\": 50,\"currency\": \"USD\"}}],\"applied_taxes\": [{\"uid\":
\"CF71CFB6-CDC4-447B-8A5D-5C5423125B14\",\"tax_uid\":
\"E0AB051C-A7CA-48F1-A8CE-

**Comment by jjc235** [comment]
Hi!  Is there any update on this?

**Comment by zenmasterjobo** [comment]
Hi @jjc235 

It's been a while, and just wondering if this issue is still persisting for you on more recent SDKs?

In the future I would recommend that you post questions on our [Developer Forums](https://developer.squareup.com/forums) instead, as these forums are monitored by Square employees, and response times are within 48 hours.
