### ISSUE TITLE
ordersApi.updateOrder is failing with `API Error Argument for 'orderId' failed validation`

### ISSUE THREAD

**Issue by emil-alexandrescu** [square/square-nodejs-sdk#27]
I am trying to update order, but it's currently failing with following error.

```
API Error Argument for 'orderId' failed validation.
Expected value to be of type 'string' but found 'undefined'.
Given value: undefined
```

I can confirm orderId is string value - `JJMMMmM...Ib8AsYGAr98cd8YY`.

```js
client.ordersApi.updateOrder(orderId, {
      fieldsToClear: 'line_items[some_line_item_field]',
      order: {
        locationId: 'some_location_id',
        version: 2
      }
    })
```

It seems like it is failing at validating request, not even sending the request. I could see same request is working fine on API explorer.

**Comment by StephenJosey** [comment]
Which version of the SDK are you using? In older versions, `locationId` was the first parameter, I believe, so if you're using an older version it's probably not setting the `orderId` at all in the above parameter list.

**Comment by emil-alexandrescu** [comment]
@StephenJosey I am using latest - 9.1.0

**Comment by StephenJosey** [comment]
Can you share your application id? I'm unable to replicate this so far. I used your exact code above (besides changing out the uid and a specific field), and it worked fine with 9.1.0.

**Comment by emil-alexandrescu** [comment]
It's `sandbox-sq0idb-pL6jm6kCntWK5OaB_QGI8A` @StephenJosey

**Comment by StephenJosey** [comment]
Thanks, I do not see errors on our side so you're right it's not making the request at all. It sounds like for whatever reason `orderId` is undefined at the time of the `updateOrder` call. If you do `console.log(orderId)` right before the call, does it print out the id successfully?

**Comment by emil-alexandrescu** [comment]
@StephenJosey Yes I tried that right before making `updateOrder` call, and it's printing string value correctly.

**Comment by StephenJosey** [comment]
I'm not sure what else it could be, then, and I'm not able to replicate. Based on the error, the value is undefined, and since it's not hitting our servers, I'm not able to debug it further on my side unfortunately.

Curious if you hardcoded a string value instead of the variable, does it work?

**Comment by emil-alexandrescu** [comment]
@StephenJosey I got same error even with hardcoded string. I think it's currently failing when validating parameter inside the library before sending request to server. 

FYI, the error is happening here
```
at DefaultRequestBuilder.prepareArgs (/node_modules/square/dist/square.cjs.development.js:16164:11)
```

To replicate the issue, you can import from dist version of the library and try calling `updateOrder` with minimal parameters.

**Comment by wolfadex** [comment]
@emil-alexandrescu hi, I wanted to check in and see if this is still an issue for you. If so I'd like to dive in again and try and replicate and fix it. If not I'd like to close this issue.

**Comment by zenmasterjobo** [comment]
@emil-alexandrescu I am closing this issue due to prolonged inactivity, feel free reopen it if you are still experiencing the problem and would like further assistance.
