### ISSUE TITLE
Example (as JSON) showing wrong property format on models

### ISSUE THREAD

**Issue by mootrichard** [square/square-nodejs-sdk#4]
The models don't match the properties listed above them. It looks like the JSON examples are still using the snake case instead of camel case.

Here is an example:
https://github.com/square/square-nodejs-sdk/blob/master/doc/models/address.md#example-as-json

**Comment by jessdelacruzsantos** [comment]
The format shown is of the JSON payload sent to Square's API. It is not an example of input for the SDK. Sorry about the confusion.
