### ISSUE TITLE
2 Payment Forms Show Instead of 1 in React Component Render

### ISSUE THREAD

**Issue by stalliw** [square/square-nodejs-sdk#44]
I'm experiencing a minor bug in the Payment Form that will add the ability for customers to pay by debit or credit card. I am using React/Node. 

I've added the Square-provided script in my React index.html file. I then created a separate React Component js file to render the Payment Form. It all works except two payment forms appear when I only have one "payment-form" container. See below. 

![image](https://user-images.githubusercontent.com/72957360/124415037-f5a7b480-dd21-11eb-8989-f592d145c283.png)

![image](https://user-images.githubusercontent.com/72957360/124415057-05bf9400-dd22-11eb-80fe-c98bfba836d1.png)

I'm not sure why two payment forms pop up. When i include everything (script to access square, script to access payment form) in my index.html file only - it works perfect & I only get one form. However, I'm kind of new to this and keep seeing that I don't want to add too much t that .html file. Any help?

Many thanks!

**Comment by SYED-RAFI-NAQVI** [comment]
Hey @stalliw 

I am glad you asked it. Recently I have had to tackle this problem while integrating payments. I guess the react component is rendering twice. You can use the `useEffect's` dependency array to resolve this issue.
