### ISSUE TITLE
Inconsistence types for `createCard` api ?

### ISSUE THREAD

**Issue by rawatnaresh** [square/square-nodejs-sdk#47]
The [`Card`](https://github.com/square/square-nodejs-sdk/blob/200bdf2e41453a1f0a183d11f88fe78992dc872b/src/models/createCardRequest.ts#L29) type that is used in `CreateCardRequest` has [`customerId`](https://github.com/square/square-nodejs-sdk/blob/200bdf2e41453a1f0a183d11f88fe78992dc872b/src/models/card.ts#L38) marked as optional but it should be required as calling `createCard` without `customerId` throws an error

- Throws Error
```js

await cardsApi.createCard({
    idempotencyKey: 'unique_key',
    sourceId: 'nonce',
    card: { }, // throws error although card.customerId is marked as optional
 });

```
- Works fine
```js
await cardsApi.createCard({
    idempotencyKey: 'unique_key',
    sourceId: 'nonce',
    card: { customerId: 'customer_id' }, // customerId should be passed although its marked a optional
 });

```

**Comment by wolfadex** [comment]
@rawatnaresh sorry about the confusion around this. The docs are correct, though they could be more clear. I've reached out to the respective team about adding more clarity around this.
