### ISSUE TITLE
How Call API's directly from Frontend(React)

### ISSUE THREAD

**Issue by arjun-gurumoorthy** [square/square-nodejs-sdk#72]
I wants to directly access a Endpoint: https://connect.squareupsandbox.com/v2/locations from my React application directly without using backend. How can we achieve this. When we tried to access we have got the CORS origin issue

**Comment by wolfadex** [comment]
Unfortunately these are server only SDKs as they require an authentication token that you don't want to expose to your users. Noted in [the Requirements section](https://github.com/square/square-nodejs-sdk#requirements).

Is there any way we could change this to make it more apparent?

---

If you're concerned about the work required to setup a full backend, you could look into using a serverless solution.
