### ISSUE TITLE
Update Catalog Object Response with latest Example

### ISSUE THREAD

**Issue by Ral15** [square/square-nodejs-sdk#79]
Response at Documentation is different from what the SDK is returning for Catalog Object Responses.

https://developer.squareup.com/explorer/square_2022-02-16/catalog-api/list-catalog

Missing ecom data

**Comment by zenmasterjobo** [comment]
Hi @Ral15 - sorry to inform so late, but the ecom data fields were not intended to be released on the public API, and as such will continue to not be supported going forward.
