### ISSUE TITLE
Export apimatic schemas for models

### ISSUE THREAD

**Issue by Leichtwind** [square/square-nodejs-sdk#8]
I would like to use this package to work with Webhooks API. It contains both typing definitions and `apimatic` schemas for models, that nicely suits my needs. But unfortunately, the schemas are not exported. Can you please export the schemas as well?

**Comment by StephenJosey** [comment]
Thanks for the feedback! I will pass this along to our SDK team and let you know once I have more info.

**Comment by sseaman** [comment]
Would the swagger spec (https://github.com/square/connect-api-specification) help you?  It sounds like you'd like to use the spec to interpret the results in the Webhooks event body?

**Comment by Leichtwind** [comment]
@sseaman We are using TypeScript. I want to use the interfaces from the package for the typings for the webhook events processing.
Before I can do it, the webhook response should be transformed via apimatic (as it is done in the SDK).
The issue is that the corresponding apimatic schemas are not exported.

**Comment by sseaman** [comment]
I've added this to our feature backlog but I do not expect us to get anytime soon.  If you require this in the next few months, I'd suggest investigating other alternatives.  Apologies.

**Comment by sseaman** [comment]
I'm going to close this for now but it is on our internal backlog.  Thank you for the suggestion!
