### ISSUE TITLE
TS2322: Type 'StrictObjectSchema<string, { category: ["category", Schema<string, string>]; code: ["code", Schema<string, string>]; detail: ["detail", Schema<string, string>]; field: [...]; }>' is not assignable to type 'Schema<Error, any>'.   The types returned by 'map(...)' are incompatible between these types.     Type '{ category?: string; code?: string; detail?: string; field?: string; }' is not assignable to type 'Error'.       Property 'category' is optional in type '{ category?: string; code?: string; detail?: string; field?: string; }' but required in type 'Error'.

### ISSUE THREAD

**Issue by liftyourgame** [square/square-nodejs-sdk#88]
Getting a typescript compile error on:

node_modules/square/src/models/error.ts

TS2322: Type 'StrictObjectSchema<string, { category: ["category", Schema<string, string>]; code: ["code", Schema<string, string>]; detail: ["detail", Schema<string, string>]; field: [...]; }>' is not assignable to type 'Schema<Error, any>'.   The types returned by 'map(...)' are incompatible between these types.     Type '{ category?: string; code?: string; detail?: string; field?: string; }' is not assignable to type 'Error'.       Property 'category' is optional in type '{ category?: string; code?: string; detail?: string; field?: string; }' but required in type 'Error'.

On node v14.18.3

typescript 4.4.4

**Comment by liftyourgame** [comment]
skipLibChecks is off

https://stackoverflow.com/questions/42934675/why-tsc-shows-the-errors-on-dependency-module-typings

**Comment by liftyourgame** [comment]
I'm using nextjs and running:
next build
That triggered this error.
As a temporary workaround I can set:
    typescript: {
      ignoreBuildErrors: true
    },

And can then get a build but I'd like to make the typescript checking work again.

Seems to be a difference in types from node_modules/square/src/models/error.ts and node_modules/@apimatic/schema/src/types/object.ts

error.ts designates that 'category' is required but the @apimatic thinks it's optional.

**Comment by liftyourgame** [comment]
https://nextjs.org/docs/api-reference/next.config.js/ignoring-typescript-errors

**Comment by wolfadex** [comment]
@liftyourgame thank you for reporting this. Our SDK team is looking into this further.

**Comment by zenmasterjobo** [comment]
Hi @liftyourgame,

Just checking in to see if you are still experiencing this issue.

**Comment by liftyourgame** [comment]
Not really using it so don't know if its still an issue

**Comment by zenmasterjobo** [comment]
Closing this issue for now. Anyone is welcome to re-open if they can reproduce or provide further information. Thank you!
