### ISSUE TITLE
Order status and Reward status not automatically changing after successful payment

### ISSUE THREAD

**Issue by michaelcaterisano** [square/square-nodejs-sdk#9]
Hi. I'm using the Orders API, Loyalty API, and Payments API in my application. I'm creating an order, then creating a loyalty reward and associating it with the order_id, then creating a payment and also associating it with the order_id. After doing this, the payment state is "COMPLETED", but the order state is still "OPEN" instead of "COMPLETED", and the reward state is still "ISSUED" instead of "REDEEMED". The docs say that the order and reward states should automatically change to "COMPLETED" and "REDEEMED", respectively, after a payment is created and associated with an order using the order_id. Here's the pseudocode for what I'm doing:
```
order = createOrder({orderInfo})
reward = createLoyaltyReward({
    reward: {
      loyaltyAccountId: some-id,
      rewardTierId: some-id,
      orderId: order.id
    },
    idempotencyKey: 'some-id'
  })
payment = createPayment(...info, order.id)
```
When I check the payment by calling `paymentsApi.getPayment(payment.id)`, I can see that the payment state is "COMPLETED". When I check `ordersApi.retrieveOrder(order.id)`, the order tate is "OPEN", but it is associated with the payment and the loyalty reward that I created. When I check `loyaltyApi.retrieveReward(reward.id)`, the status is "ISSUED", when I expect it to be "REDEEMED".
The order is successfully making it through to my sandbox environment, and so is the loyalty reward. Loyalty points are successfully being deducted from the loyalty account. I'm just confused about why the state property on the response objects for the order and the reward are not changing when I create the payment.

**Comment by StephenJosey** [comment]
Did the order have fulfillments associated with it? If so, I believe you will need to close out the order either via the Square Dashboard, Square POS, or manually via the API by updating the state. If there was no fulfillment, then it should be marked as `COMPLETED` automatically when it's fully paid for as far as I know. If that's the case, please provide an `order_id` so I can check our logs.

**Comment by michaelcaterisano** [comment]
That was it, thanks! This was all in the sandbox environment and I wasn't aware I could mock the fulfillment as well. Selecting "Mark Picked Up" on the order in the sandbox dashboard did the trick. The order status is now "COMPLETED" and the reward status is "REDEEMED" as expected.
