### ISSUE TITLE
Is a booking id really an optional property of a booking?

### ISSUE THREAD

**Issue by chris-miner** [square/square-nodejs-sdk#90]
The Booking interface declares its id property as optional:
```
export interface Booking {
    /** A unique ID of this object representing a booking. */
    id?: string;
```
Is this really optional?  Don't all bookings have an id?  Can't I expect that a booking fetched from square will have an id?

**Comment by wolfadex** [comment]
It's marked as optional because the same `Booking` type is used for both in the request and response. In the request you don't pass it, but it should always be returned in the response.
